# Generated by Django 5.0.4 on 2026-02-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creators", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorprofile",
            name="bank_account_holder",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="bank_account_type",
            field=models.CharField(
                blank=True,
                choices=[("checking", "Checking"), ("savings", "Savings")],
                default="checking",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="bank_country",
            field=models.CharField(blank=True, default="US", max_length=2),
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="bank_routing_number",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
