# Generated by Django 5.0.4 on 2026-02-21 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creators", "0003_add_banking_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "goal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional fundraising goal in USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jars",
                        to="creators.creatorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("creator", "slug")},
            },
        ),
    ]
