# Generated by Django 5.0.4 on 2026-02-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creators", "0004_add_jar_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creatorprofile",
            name="tip_goal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly tip goal in ZAR (Rands)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jar",
            name="goal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional fundraising goal in ZAR (Rands)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
