# Generated by Django 5.0.4 on 2026-02-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creators", "0005_alter_creatorprofile_tip_goal_alter_jar_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorprofile",
            name="paystack_subaccount_code",
            field=models.CharField(
                blank=True,
                help_text="Paystack subaccount code (ACCT_xxxx) — auto-created on bank detail save",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="paystack_subaccount_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
