from django.urls import path

from .views import (
    AdminKycApproveView,
    AdminKycDeclineView,
    CreatorDetailView,
    CreatorIncomingPledgesView,
    CreatorListView,
    MarkNotificationsReadView,
    MyCommissionRequestDetailView,
    MyCommissionRequestListView,
    MyCommissionSlotView,
    MyCreatorProfileView,
    MyDashboardStatsView,
    MyJarDetailView,
    MyJarListCreateView,
    MyKycDocumentListCreateView,
    MyMilestoneDetailView,
    MyMilestoneListCreateView,
    MyNotificationsView,
    MyPostDetailView,
    MyPostListCreateView,
    MyTierDetailView,
    MyTierListCreateView,
    PostAccessView,
    PublicCommissionRequestCreateView,
    PublicCreatorJarsView,
    PublicJarDetailView,
    PublicMilestoneListView,
    PublicPostListView,
    PublicTierListView,
)

urlpatterns = [
    path("", CreatorListView.as_view(), name="creator-list"),
    path("me/", MyCreatorProfileView.as_view(), name="my-creator-profile"),
    path("me/stats/", MyDashboardStatsView.as_view(), name="my-dashboard-stats"),
    path("me/notifications/", MyNotificationsView.as_view(), name="my-notifications"),
    path("me/notifications/read/", MarkNotificationsReadView.as_view(), name="my-notifications-read"),
    path("me/jars/", MyJarListCreateView.as_view(), name="my-jar-list"),
    path("me/jars/<int:pk>/", MyJarDetailView.as_view(), name="my-jar-detail"),
    path("me/posts/", MyPostListCreateView.as_view(), name="my-post-list"),
    path("me/posts/<int:pk>/", MyPostDetailView.as_view(), name="my-post-detail"),
    path("me/tiers/", MyTierListCreateView.as_view(), name="my-tier-list"),
    path("me/tiers/<int:pk>/", MyTierDetailView.as_view(), name="my-tier-detail"),
    path("me/milestones/", MyMilestoneListCreateView.as_view(), name="my-milestone-list"),
    path("me/milestones/<int:pk>/", MyMilestoneDetailView.as_view(), name="my-milestone-detail"),
    path("me/commission-slot/", MyCommissionSlotView.as_view(), name="my-commission-slot"),
    path("me/commissions/", MyCommissionRequestListView.as_view(), name="my-commissions"),
    path("me/commissions/<int:pk>/", MyCommissionRequestDetailView.as_view(), name="my-commission-detail"),
    path("me/kyc/", MyKycDocumentListCreateView.as_view(), name="my-kyc-docs"),
    path("admin/<int:pk>/kyc/approve/", AdminKycApproveView.as_view(), name="admin-kyc-approve"),
    path("admin/<int:pk>/kyc/decline/", AdminKycDeclineView.as_view(), name="admin-kyc-decline"),
    path("me/pledges/", CreatorIncomingPledgesView.as_view(), name="creator-pledges"),
    path("<slug:slug>/jars/", PublicCreatorJarsView.as_view(), name="creator-jars"),
    path("<slug:slug>/jars/<slug:jar_slug>/", PublicJarDetailView.as_view(), name="creator-jar-detail"),
    path("<slug:slug>/posts/", PublicPostListView.as_view(), name="creator-posts"),
    path("<slug:slug>/posts/access/", PostAccessView.as_view(), name="creator-posts-access"),
    path("<slug:slug>/tiers/", PublicTierListView.as_view(), name="creator-tiers"),
    path("<slug:slug>/milestones/", PublicMilestoneListView.as_view(), name="creator-milestones"),
    path("<slug:slug>/commission-requests/", PublicCommissionRequestCreateView.as_view(), name="creator-commission-requests"),
    path("<slug:slug>/", CreatorDetailView.as_view(), name="creator-detail"),
]
