# Generated by Django 5.0.4 on 2026-02-21 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creators", "0004_add_jar_model"),
        ("tips", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tip",
            name="jar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jar_tips",
                to="creators.jar",
            ),
        ),
    ]
