# Generated by Django 5.0.4 on 2026-02-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tips", "0003_add_jar_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="tip",
            name="creator_net",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="tip",
            name="paystack_reference",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name="tip",
            name="platform_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="tip",
            name="service_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
